# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noticeProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import *
import csv


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # 화면에 출력되는 위치 설정
        MainWindow.setGeometry(200, 100, 1040, 750)
        # 화면 중앙에 mainwindow 위치하도록 하는 함수 호출
        self.center(MainWindow)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(405, 20, 220, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(940, 30, 71, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(128, 670, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(356, 670, 100, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(584, 670, 100, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(812, 670, 100, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 65, 1001, 591))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "공지사항"))
        self.label.setText(_translate("MainWindow", "컴퓨터정보공학과 공지사항"))
        font = self.label.font()
        font.setPointSize(10)
        # font.setBold(True)
        self.label.setFont(font)
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_2.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "3"))
        self.pushButton_5.setText(_translate("MainWindow", "4"))

    # 화면 중앙에 mainwindow 위치하도록 하는 코드
    def center(self, Mainwindow):
        qr = Mainwindow.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        Mainwindow.move(qr.topLeft())


class MainClass(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        # UI 선언
        main_ui = Ui_MainWindow()
        # UI 준비
        main_ui.setupUi(self)
        self.setTableWidgetData(main_ui.tableWidget)
        # 화면을 보여 준다.
        self.show()

    def setTableWidgetData(self, tableWidget):
        # csv 파일 정보를 list로 받아옴
        noticeInfo = self.loadNoticeInfo()
        # 행/열 개수 설정
        tableWidget.setRowCount(len(noticeInfo))
        tableWidget.setColumnCount(5)
        # 행의 폭을 열 마다 다르게 조정
        tableWidget.setColumnWidth(0, int(self.width() * 15 / 30))
        tableWidget.setColumnWidth(1, int(self.width() * 3 / 30))
        tableWidget.setColumnWidth(2, int(self.width() * 3 / 30))
        tableWidget.setColumnWidth(3, int(self.width() * 4 / 30))
        tableWidget.setColumnWidth(4, int(self.width() * 2 / 30))
        # 열 이름 붙이는 부분®
        colum_title = ["제목", "작성일", "수정일", "기재한 곳", "조회수"]
        tableWidget.setHorizontalHeaderLabels(colum_title)
        # 리스트 테이블 내용 입력
        list_seq = 0
        row = 0
        column = 0
        url = ""
        for i in noticeInfo:
            for j in i:
                # url
                if list_seq == 0:
                    url = j
                # 제목
                elif list_seq == 1:
                    label1 = QLabel()
                    label1.setText('<a href="'+url+'">'+j+'</a>')
                    label1.setOpenExternalLinks(True)
                    tableWidget.setCellWidget(column, row, label1)
                    row += 1
                else:
                    tableWidget.setItem(column, row, QTableWidgetItem(j))
                    row += 1
                list_seq += 1
            list_seq = 0
            row = 0
            column += 1

    # csv 파일로 부터 정보를 불러 오는 부분
    def loadNoticeInfo(self) -> list:
        filename = "noticeTitle.csv"
        f = open(filename, "r", encoding="utf-8-sig")
        rdr = csv.reader(f)
        a = []
        for i in rdr:
            a.append(i)
        f.close()
        return a


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
